In [199]:
import matplotlib.pyplot as plt

In [200]:
import mpl_toolkits.mplot3d

In [201]:
import numpy as np

In [202]:
from sklearn import datasets, decomposition

In [203]:
cancer = datasets.load_breast_cancer()
X= cancer.data
Y= cancer.target
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [204]:
fig = plt.figure(1, figsize=(7,5))
plt.clf()

<Figure size 700x500 with 0 Axes>

In [205]:
ax = fig.add_subplot(111, projection= '3d', elev= 48,azim=134)
ax.set_position([0,0,0.95,1])

In [206]:
plt.clf()

<Figure size 640x480 with 0 Axes>

In [207]:
pca = decomposition.PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [208]:
X=pca.transform(X)
X

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [216]:
y = cancer.target

In [217]:
for name, label in [("Benign", 0), ("Malignant", 1)]:
    ax.text3D(
        X[y == label, 0].mean(),
        X[y == label, 1].mean(),
        X[y == label, 2].mean(),
        name,
        horizontalalignment='center',
        bbox=dict(alpha=0.5, edgecolor='w', facecolor='w'),
    )

plt.show()


IndexError: index 2 is out of bounds for axis 1 with size 2

In [218]:
y = np.choose(y, [1,2,0]).astype(float)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 2., 2.,
       2., 2., 1., 1., 2., 1., 1., 2., 2., 2., 2., 1., 2., 1., 1., 2., 2.,
       2., 2., 1., 2., 1., 1., 2., 1., 2., 1., 1., 2., 2., 2., 1., 1., 2.,
       1., 1., 1., 2., 2., 2., 1., 2., 2., 1., 1., 2., 2., 2., 1., 1., 2.,
       2., 2., 2., 1., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 1., 1.,
       1., 2., 1., 1., 2., 2., 2., 1., 1., 2., 1., 2., 1., 1., 2., 1., 1.,
       2., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 1., 2., 2., 2., 2., 1., 1., 2., 1., 2., 2., 1., 1., 2.,
       2., 1., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1., 1., 2., 1., 2., 1.,
       2., 2., 2., 1., 2., 2., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1.,
       2., 1., 2., 1., 2., 2., 1., 2., 1., 1., 1., 1., 2., 2., 1., 1., 2.,
       2., 2., 1., 2., 2.

In [219]:
ax.scatter(X[:,0],X[:,1],X[:,2], c=y, cmap= plt.cm.nipy_spectral, edgecolor = 'k' )

ax.xaxis.set_ticklabels([])
ax.yaxis.set_ticklabels([])
ax.zaxis.set_ticklabels([])
plt.show()

IndexError: index 2 is out of bounds for axis 1 with size 2